### ISSUE TITLE
Fix namespaces

### ISSUE THREAD

**Issue by Tegon-McCloud** [xdHampus/Den-Digitale-Proevevagt#1]
Tror du er kommet til at smide DpvClassLibrary.Configuration og de andre DpvClassLibrary.* mapper ind i DpvClassLibrary.DpvClassLibrary. Kan du eventuelt lige rykke dem ud?

**Comment by xdHampus** [comment]
Havde ikke set at de var indsat forkert, tak for henvendelsen.

Har flyttet dem og det burde fungere nu.
